site_name: Solution Documentation
repo_url: 'https://github.com/SoFairOA/solution_documentation'
edit_uri_template: 'blob/main/docs/{path}'
nav:
  - Home: index.md
  - 'Website': 01-website.md
  - 'Workflow': 02-workflow.md
  - 'Dataset': 03-dataset.md
  - 'Software Mention Extraction and Disambiguation': 04-software-mention-extraction-and-disambiguation.md
  - 'Use Cases': 05-use-cases.md
theme: readthedocs
copyright: Copyright &copy; 2024-2025 SoFAIR Contributors.
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - footnotes
plugins:
  - mermaid2
  - search
extra_css:
  - css/extra.css
extra_javascript:
  - js/clipboard.min.js
  - js/extra.js
